### ISSUE TITLE
Error in register() / global_optimization

### ISSUE THREAD

**Issue by folterj** [multiview-stitcher/multiview-stitcher#78]
When calling `register()` using `global_optimization`, an error can occur if an `estimate()` function is called.
`Affine_Fit()` can return a boolean.

Multiview-stitcher version: 0.1.29

```
    reg_result = registration.register(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\muvis-align-env\Lib\site-packages\multiview_stitcher\registration.py", line 1833, in register
    params, groupwise_resolution_info_dict = groupwise_resolution(
                                             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\muvis-align-env\Lib\site-packages\multiview_stitcher\registration.py", line 926, in groupwise_resolution
    return groupwise_resolution_global_optimization(g_reg, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\muvis-align-env\Lib\site-packages\multiview_stitcher\registration.py", line 1155, in groupwise_resolution_global_optimization
    optimize_bead_subgraph(
  File "C:\ProgramData\miniconda3\envs\muvis-align-env\Lib\site-packages\multiview_stitcher\registration.py", line 1464, in optimize_bead_subgraph
    transform_generator.estimate(node_pts, adj_pts)
  File "C:\ProgramData\miniconda3\envs\muvis-align-env\Lib\site-packages\multiview_stitcher\transforms.py", line 63, in estimate
    Affine_Fit(src, dst).Matrix()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'Matrix'

```

**Comment by m-albert** [comment]
Hm is it possible that the `msims` you pass to `register()` function have different spatial dimensionality? I.e. that some are 2D and some 3D?

**Comment by m-albert** [comment]
Closing after offline discussion as this is addressed by adding more informative error handling introduced in https://github.com/multiview-stitcher/multiview-stitcher/pull/80
